/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Dusty({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/foliage/dustycp.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={-0.06}>
        <mesh geometry={nodes.Cylinder014.geometry} material={materials['1hourglas_Intrnd']} />
        <mesh geometry={nodes.Cylinder014_1.geometry} material={materials['1hourglas_Petiole']} />
        <mesh geometry={nodes.Cylinder014_2.geometry} material={materials['1hourglas_Leaf']} />
        <mesh geometry={nodes.Cylinder014_3.geometry} material={materials['1hourglas_Mrstm']} />
        <mesh geometry={nodes.Cylinder014_4.geometry} material={materials['Material.060']} />
        <mesh geometry={nodes.Cylinder014_5.geometry} material={materials['Material.059']} />
      </group>
    </group>
  )
}

useGLTF.preload('/foliage/dustycp.glb')
