/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Fern({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/foliage/ferncp.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 0, -0.01]} rotation={[0.22, 0, 0]} scale={[0.08, 0.07, 0.08]}>
        <mesh geometry={nodes.Cylinder011.geometry} material={materials['Material.051']} />
        <mesh geometry={nodes.Cylinder011_1.geometry} material={materials['Material.052']} />
      </group>
    </group>
  )
}

useGLTF.preload('/foliage/ferncp.glb')
