/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Silvers({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/foliage/silverscp.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes['1hourglas_1'].geometry} material={materials['1hourglas_Petiole']} />
        <mesh geometry={nodes['1hourglas_2'].geometry} material={materials['1hourglas_Petiole']} />
        <mesh geometry={nodes['1hourglas_3'].geometry} material={materials['1hourglas_Leaf']} />
        <mesh geometry={nodes['1hourglas_4'].geometry} material={materials['1hourglas_Mrstm']} />
      </group>
    </group>
  )
}
