/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Vase3({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/vase/vase3cp.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.yellow_vase.geometry} material={materials['Material.002']} position={[0, 0, -0.01]} scale={[0.3, 0.76, 0.3]} />
    </group>
  )
}