/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Vase1({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/vase/vase1cp.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.white_vase.geometry} material={materials['Material.058']} position={[0, 0, -0.01]} scale={[0.52, 0.68, 0.38]} />
    </group>
  )
}

useGLTF.preload('/vase/vase1cp.glb')
