/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Vase2({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/vase/vase2cp.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.worange_vase.geometry} material={materials['Material.056']} position={[0, 0, -0.01]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.44, 0.44, 0.53]} />
    </group>
  )
}

useGLTF.preload('/vase/vase2cp.glb')
