/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Cosmospurple({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/filler/cosmos/cosmospurplecp.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={0.03}>
        <mesh geometry={nodes.Cylinder192.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Cylinder192_1.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Cylinder192_2.geometry} material={materials['Material.009']} />
      </group>
    </group>
  )
}
