/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Sunflower({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('..//sunflowercp.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Sphere.geometry} material={materials['Material.001']} position={[0.46, 26.97, 7.17]} rotation={[-2.02, -0.08, 0.08]} scale={[3.06, 3.06, 2.32]} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Material.002']} position={[0, -1.5, 10.06]} />
      <mesh geometry={nodes.Sphere001.geometry} material={materials['Material.003']} position={[-3.31, 58.42, -0.42]} rotation={[-1.57, -1.53, 0]} scale={[3.06, 5.27, 2.32]} />
      <mesh geometry={nodes.Sphere002.geometry} material={materials['Material.003']} position={[-3.24, 60.23, 22.24]} rotation={[-Math.PI / 2, -1.53, Math.PI]} scale={[3.06, 5.27, 2.32]} />
      <mesh geometry={nodes.Sphere003.geometry} material={materials['Material.003']} position={[-2.67, 69.93, 10.5]} rotation={[-1.57, -1.53, -1.57]} scale={[3.06, 5.27, 2.32]} />
      <mesh geometry={nodes.Sphere004.geometry} material={materials['Material.003']} position={[-3.72, 48.4, 10.97]} rotation={[-Math.PI / 2, -1.53, 1.57]} scale={[3.06, 5.27, 2.32]} />
      <mesh geometry={nodes.Sphere005.geometry} material={materials['Material.003']} position={[-2.93, 67.67, 3.48]} rotation={[-Math.PI / 2, -1.53, -0.78]} scale={[3.06, 5.27, 2.32]} />
      <mesh geometry={nodes.Sphere006.geometry} material={materials['Material.003']} position={[-3.58, 51.68, 18.19]} rotation={[-Math.PI / 2, -1.53, 2.36]} scale={[3.06, 5.27, 2.32]} />
      <mesh geometry={nodes.Sphere007.geometry} material={materials['Material.003']} position={[-2.91, 68.28, 17.52]} rotation={[-Math.PI / 2, -1.53, -2.35]} scale={[3.06, 5.27, 2.32]} />
      <mesh geometry={nodes.Sphere008.geometry} material={materials['Material.003']} position={[-3.58, 51.8, 2.76]} rotation={[-Math.PI / 2, -1.53, 0.79]} scale={[3.06, 5.27, 2.32]} />
      <mesh geometry={nodes.Sphere009.geometry} material={materials['Material.004']} position={[-2.22, 63.42, 0.62]} rotation={[-1.57, -1.53, -0.39]} scale={[3.06, 5.27, 2.32]} />
      <mesh geometry={nodes.Sphere010.geometry} material={materials['Material.004']} position={[-2.52, 55.91, 21]} rotation={[-Math.PI / 2, -1.53, 2.75]} scale={[3.06, 5.27, 2.32]} />
      <mesh geometry={nodes.Sphere011.geometry} material={materials['Material.004']} position={[-1.92, 70.7, 13.82]} rotation={[-Math.PI / 2, -1.53, -1.96]} scale={[3.06, 5.27, 2.32]} />
      <mesh geometry={nodes.Sphere012.geometry} material={materials['Material.004']} position={[-2.79, 49.26, 6.5]} rotation={[-Math.PI / 2, -1.53, 1.18]} scale={[3.06, 5.27, 2.32]} />
      <mesh geometry={nodes.Sphere013.geometry} material={materials['Material.004']} position={[-1.93, 70.47, 7.77]} rotation={[-Math.PI / 2, -1.53, -1.18]} scale={[3.06, 5.27, 2.32]} />
      <mesh geometry={nodes.Sphere014.geometry} material={materials['Material.004']} position={[-2.81, 48.75, 13.92]} rotation={[-Math.PI / 2, -1.53, 1.96]} scale={[3.06, 5.27, 2.32]} />
      <mesh geometry={nodes.Sphere015.geometry} material={materials['Material.004']} position={[-2.17, 64.52, 20.03]} rotation={[-1.57, -1.53, -2.75]} scale={[3.06, 5.27, 2.32]} />
      <mesh geometry={nodes.Sphere016.geometry} material={materials['Material.004']} position={[-2.54, 55.55, 0.23]} rotation={[-1.57, -1.53, 0.39]} scale={[3.06, 5.27, 2.32]} />
      <mesh geometry={nodes.Sphere017.geometry} material={materials['Material.005']} position={[-3.28, 59.78, 10.74]} rotation={[0, 0, -0.04]} scale={[2.44, 7.43, 7.43]} />
      <mesh geometry={nodes.Sphere018.geometry} material={materials['Material.001']} position={[-0.66, 39.15, 13.51]} rotation={[-1.03, 0.15, 3]} scale={[3.06, 3.06, 2.32]} />
      <mesh geometry={nodes.Sphere019.geometry} material={materials['Material.001']} position={[0.42, 12.51, 12.34]} rotation={[-0.84, 0.17, -3.04]} scale={[3.06, 3.06, 2.32]} />
    </group>
  )
}

useGLTF.preload('..//sunflowercp.glb')
