/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Anemonewhite({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/focal/anemone/anemonewhitecp.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes['12973_anemone_flower_v1_l2'].geometry} material={materials['12973_anemone_flower']} rotation={[2.48, -1.5, 2.23]} scale={0.15} />
    </group>
  )
}

useGLTF.preload('/focal/anemone/anemonewhitecp.glb')
