/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Gypsy({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/filler/gypsycp.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={1.38}>
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials['Material.045']} />
        <mesh geometry={nodes.Cylinder_2.geometry} material={materials['Material.001']} />
      </group>
    </group>
  )
}
