/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Gypsy({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/filler/gypsycp.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 0, -0.01]} rotation={[2.2, 0.87, -2.8]} scale={0.01}>
        <mesh geometry={nodes.Cylinder010.geometry} material={materials['Material.045']} />
        <mesh geometry={nodes.Cylinder010_1.geometry} material={materials['Material.050']} />
        <mesh geometry={nodes.Cylinder010_2.geometry} material={materials['Material.046']} />
      </group>
    </group>
  )
}

useGLTF.preload('/filler/gypsycp.glb')
